apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-story-deployment
spec:
  selector:
    matchLabels:
      app: node-story
  replicas: 2
  template:
    metadata:
      labels:
        app: node-story
    spec:
      containers:
        - name: node-story-container
          image: 17200082/node-k8s-app:storyv2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: story-data-configmap
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: story-host-pvc
